services:
  - type: web
    name: allegro-scraper
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget gnupg2
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable xvfb
      pip install -r requirements.txt
    startCommand: |
      Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
      gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DISPLAY
        value: ":99.0"
      - key: SELENIUM_MANAGER
        value: "true"
    autoDeploy: true
